export const learningThemes = [
  {
    id: '889ef737-03ad-4714-8247-11ebfe31b525',
    title: 'AI in Climate',
    image:
      'https://images.pexels.com/photos/17485678/pexels-photo-17485678/free-photo-of-an-artist-s-illustration-of-artificial-intelligence-ai-this-image-depicts-how-ai-could-be-used-in-the-field-of-sustainability-from-biodiversity-to-climate-it-was-created-by-nidia-dias.png',
    keywords: [
      'climate',
      'AI',
      'sustainability',
      'Klimaat',
      'luchtkwaliteit',
      'weerstation',
      'co2',
      'klimaat',
      'co2',
      'luchtkwaliteit',
      'temperatuur',
    ],
  },
  {
    id: '1284a170-58d3-40c3-a527-627c2b8cc640',
    title: 'Robotics',
    image:
      'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keywords: [
      'social robot',
      'AI',
      'robotics',
      'Sociale Robot',
      'vriendengroepen',
      'sociale robot',
    ],
  },
  {
    id: '4ba2e66c-5687-42ee-b6dc-53939f9b7c26',
    title: 'AI in Healthcare',
    image:
      'https://cdn.prod.website-files.com/65c37e1a9189104bf8d071be/66faedc74ffa833d72a30331_8.png',
    keywords: ['healthcare', 'AI', 'medicine', 'Thermostaat', 'triage', 'zorg'],
  },
  {
    id: 'e2fe67f3-b545-4b4c-b81a-f3d6c05b167e',
    title: 'Language Technology',
    image:
      'https://www.upf.edu/documents/10193/277132547/ImatgearxiuBaroni.jpg/cbd38e7f-8351-fa82-f6ae-de9fbdd14437',
    keywords: [
      'language',
      'AI',
      'technology',
      'ASCII',
      'String',
      'Taaltechnologie',
      'char',
      'levenshtein',
      'string',
      'taal',
      'taaltechnologie',
      'tekst generatie',
      'tekstueel',
    ],
  },
  {
    id: '2abb2c99-ae7b-449e-af23-5e37fb98deaf',
    title: 'Programming & Computational Thinking',
    image:
      'https://cdn.discordapp.com/attachments/1345516706134491268/1374077308725362730/AdobeStock_1065716654.jpeg?ex=682cbcb7&is=682b6b37&hm=1232c4761df46b2206c327c4122debcc01dd64737d4304b56fe00b78c4dbe9e8&',
    keywords: [
      'python',
      'blockly',
      'pseudocode',
      'grafen',
      'lus',
      'jupyter notebook',
      'computationeel denken',
      'CSUnplugged',
      'loop',
      'variabele',
      'AlsDan',
      'AlsDanAnders',
      'else',
      'for',
      'forlus',
      'functies',
      'if',
      'lussen',
      'operatoren',
      'recursie',
      'then',
      'variabelen',
      'variabele',
      'while',
      'whilelus',
    ],
  },
  {
    id: 'c462f91c-9b73-4264-83a1-0576a604b639',
    title: 'IoT & Embedded Systems',
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Embedded_Systems_PBL.jpg',
    keywords: [
      'arduino',
      'microcontroller',
      'uart',
      'i2c',
      'lcd',
      'breadboard',
      'sd',
      'led',
      'Microcontroller',
      'StartTodwenguino',
      'StartTodwenguino, knoppen',
      'arduino',
      'breadboard',
      'dwenguino',
      'geluidssensor',
      'lcd',
      'lcd-scherm',
      'ledmatrix',
      'microcontroller',
      'pinnen',
      'sensor',
      'sonar',
      'sonar-sensor',
      'spi',
      'uart',
      'µC',
      'IoT',
      'afstand',
      'dht',
      'druk',
      'grondsensor',
      'grond-sensoren',
      'luchtvochtigheid',
      'sensor',
      'telemetrie',
      'temperatuur',
      'vocht',
    ],
  },
  {
    id: '831bf26e-9b03-4dc4-93ad-f726ee7b8982',
    title: 'AI & Machine Learning',
    image:
      'https://cdn.discordapp.com/attachments/1345516706134491268/1374077309484535939/AdobeStock_659545582.jpeg?ex=682cbcb7&is=682b6b37&hm=1d24117c346a5615503c84f640dc8e039fa828db401f60f1177becfd22328b5a&',
    keywords: [
      'neurale netwerken',
      'AI',
      'deep fake',
      'classificatie',
      'teachable machine',
      'AI',
      'AI Op School',
      'Automatische aanbevelingen',
      'Datagebaseerd',
      'Dataverzameling',
      'Neuronale netwerken',
      'Taaltechnologie',
      'Unsupervised learning',
      'VOORKENNIS',
      'WeGoSTEM',
      'algoritme',
      'basisconcepten',
      'batch normalisatie',
      'bias',
      'classificatie',
      'cluster',
      'clustering',
      'computationeel denken',
      'computationeel denken',
      'computer',
      'data',
      'dataverwerking',
      'deep fake',
      'dense',
      'dijkstra',
      'dropout',
      'ecodering',
      'encryptie',
      'exercises',
      'example1',
      'example2',
      'fine tuning',
      'flatten',
      'grafen',
      'i2c',
      'imagenet',
      'internet',
      'karger',
      'klasgesprek',
      'koningsbergen',
      'lagen',
      'leerplandoelstellingen',
      'matplotlib',
      'model',
      'monte carlo',
      'neurale netwerken',
      'netwerken',
      'operatoren',
      'programmable logic controller',
      'programmeren',
      'project',
      'real time clock',
      'regelgebaseerd',
      'restauratie',
      'rgb',
      'selectie',
      'sequencing',
      'sociale netwerken',
      'spectrale clustering',
      'spanning',
      'temperatuur',
      'toepassingen',
      'transfer learning',
      'unsigned',
      'valbeweging',
      'verwerking',
      'voorstellingen',
      'voorstelling',
      'vooroordelen',
    ],
  },
  {
    id: '296708ff-7f69-40f9-a41f-f230a5f657ea',
    title: 'Networks & Communication',
    image:
      'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keywords: ['netwerken', 'communicatie', 'serieel', 'protocol', 'web'],
  },
  {
    id: '5266d17f-c58e-43df-ba88-058bf47ab26e',
    title: 'Hardware & Electronics',
    image:
      'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keywords: ['led', 'weerstand', 'servomotor', 'buzzer', 'zoemer', 'lcd-scherm'],
  },
  {
    id: '79721a9b-166c-4221-99cc-c2065c999577',
    title: 'Ethics & Reflection',
    image:
      'https://images.pexels.com/photos/6077181/pexels-photo-6077181.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keywords: [
      'vooroordelen',
      'reflectie',
      'klasgesprek',
      'influencers',
      'Reflectie',
      'bias',
      'deep fake',
      'ethiek',
      'fout',
      'vooroordelen',
    ],
  },
  {
    id: '0fc3dd9d-7681-424d-bb62-5311fb32ae04',
    title: 'Mathematics & Logic',
    image:
      'https://images.pexels.com/photos/3729557/pexels-photo-3729557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keywords: ['grafiek', 'operatoren', 'logica', 'wiskunde', 'de bruijn', 'matplotlib'],
  },
];

let keywords = [
  'LED',
  'processor',
  'De Bruijn',
  'brute force',
  'wet van ohm',
  'python',
  'timers',
  'oefening',
  'digitale elektronica',
  'seriële communicatie',
  'grafen',
  'lus',
  'sd',
  'opslag',
  'blockly',
  'pseudocode',
  'reflectie',
  'jupyter notebook',
  'co2',
  'multimeter',
  'lussen',
  'IoT',
  'vriendengroepen',
  'forlus',
  'oefeningen',
  'netwerken',
  'dataformaat',
  'schakeling',
  'servomotor',
  'clustering',
  'char',
  'modelleren',
  'vooroordelen',
  'symbolen',
  'taaltechnologie',
  'microcontroller',
  'serieel',
  'weerstand',
  'calibratie',
  'computationeel denken',
  'luchtdruk',
  'web',
  'uart',
  'lcd-scherm',
  'triage',
  'tekstueel',
  'Neurale netwerken',
  'operatoren',
  'internet',
  'klasgesprek',
  'spanningsdeler',
  'AlsDan',
  'interrupts',
  'can',
  'wacht',
  'Voorkennis',
  'KIKS',
  'beelden',
  'Sociale robot',
  'ladder',
  'arduino',
  'commentaar',
  'bibliotheek',
  'digitalRead',
  'Klimaat',
  'RNA',
  'voorstellingen',
  'materiaal',
  'toepassingen',
  'kalibratie',
  'lagen',
  'seriële monitor',
  'Teachable machine',
  'dan',
  'Oefeningen',
  'wifi',
  'Thermostaat',
  'upload',
  'String',
  'lijnvolger',
  'Lussen',
  'restauratie',
  'afstand',
  'weerstation',
  'return',
  'functies',
  'CSUnplugged',
  'real time clock',
  'Encryptie',
  'buzzer',
  'logica',
  'beslissingsboom',
  'sd-card',
  'true',
  'RGB-led',
  'zoemer',
  'logger',
  'Computationeel denken',
  'voorbeeld2',
  'i2c',
  'encryptie',
  'unsigned',
  'GO!',
  'exercises',
  'dht',
  'programmeren',
  'practicum',
  'rgb',
  'delay',
  'meten',
  'blauw',
  'zorg',
  'ledmatrix',
  'LED13',
  'bus',
  'µC',
  'frequentieanalyse',
  'sonar',
  'luchtkwaliteit',
  'elektrisch schema',
  'vals',
  'grafiek',
  'waar',
  'example1',
  'ecodering',
  'Dataverwerking',
  'Knoppen',
  'controletheorie',
  'WeGOSTEM',
  'Sociale Robot',
  'spectrale clustering',
  'clusters',
  'UART',
  'computer',
  'neurale netwerken',
  'selectie',
  'basisconcepten',
  'serie',
  'Taaltechnologie',
  'plc',
  'geluidssensor',
  'led',
  'bitsgewijs',
  'diameter graaf',
  'robot',
  'Lam Gods',
  'notebook',
  'automatisatie',
  'editor',
  'Regelgebaseerd',
  'AI Op School',
  'loop',
  'telemetrie',
  'variabelen',
  'grondsensor',
  'stroom',
  'iteratie',
  'max pooling',
  'communicatie',
  'false',
  'AI-systeem',
  'kortsluiting',
  'CPU',
  'setup',
  'Automatische aanbevelingen',
  'deep fake',
  'koningsbergen',
  'Computationeel denken',
  'versleuteling',
  'voorbeeld',
  'Servomotor',
  'luchtvochtigheid',
  'parallel',
  'unplugged',
  'dense',
  'dropout',
  'temperatuur',
  'pinnen',
  'geheimschrift',
  'Muziek',
  'Python',
  'Fysica',
  'conditie',
  'library',
  'influencers',
  'sociale robot',
  'project',
  'bluetooth',
  'emoties',
  'uploaden',
  'Computational thinking',
  'anders',
  'grond-sensoren',
  'spanning',
  'Imagenet',
  'knoppen',
  'basisprincipes',
  'if',
  '',
  'geluid',
  'C',
  'tijd',
  'artificiële intelligentie',
  'float',
  'sonar-sensor',
  'rtc',
  'dwenguino',
  'programmable logic controller',
  'StartTodwenguino',
  'example2',
  'lcd',
  'bitsgewijze logica',
  'Transfer learning',
  'AlsDanAnders',
  'levenshtein',
  'webserver',
  'Wiskunde',
  'Microcontroller',
  'ASCII',
  'Auteursherkenning',
  'WeGoSTEM',
  'Auto',
  'exporteren',
  'int',
  'dynamisch programmeren',
  'protocol',
  'type',
  'pull-up',
  'analogRead',
  'KOV',
  'motoren',
  'keuzestructuur',
  'webapplicatie',
  'invoer',
  '3D print',
  'led-matrix',
  'tekst generatie',
  'Dataverzameling',
  'algoritme',
  'Sociale netwerken',
  'fiche',
  'AI',
  'flatten',
  'latch',
  'Datagebaseerd',
  'data',
  'microprocessor',
  'sequencing',
  'Grafisch programmeren',
  'karger',
  'while',
  'fine tuning',
  'Euleriaans pad',
  'analogWrite',
  'leds',
  'valbeweging',
  'STEM',
  'leerplandoelstellingen',
  'LCD',
  'for',
  'bias',
  'digitalWrite',
  'Digitale beelden',
  'DNA',
  'dc-motor',
  'verwerking',
  'recursie',
  'breadboard',
  'pid',
  'whilelus',
  'auteursherkenning',
  'spi',
  'Graphical programming',
  'Robot',
  'Schriftherkenning',
  'dijkstra',
  'StartTodwenguino, knoppen',
  'else',
  'zwart',
  'then',
  'datastructuur',
  'Unsupervised learning',
  'classificatie',
  'uitvoer',
  'taal',
  'batch normalisatie',
  'als',
  'monte carlo',
  'fout',
  'variabele',
  'matplotlib',
  'activiteit',
  'herhaling',
];
