name: Deploy on push to main

on:
  push:
    branches:
      - main

run-name: ${{ github.actor }} has pushed an update to ${{ github.ref }} branch 🚀

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies for all projects
        run: ./install.sh

      - name: Generate the client and migrate the database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./prisma.sh migrate deploy

      - name: Build client
        run: cd client && npm run build

      - name: Restart applications
        run: pm2 restart client server

      - name: Wait for Express to restart
        run: sleep 5

      - name: Swagger docs up and running
        run: ./test-swagger-running.sh
